default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: your_dev_db
  username: your_user
  password: your_password

test:
  <<: *default
  database: your_test_db
  username: your_user
  password: your_password

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>